# Generated by Django 4.2.13 on 2024-05-29 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium')], max_length=7)),
                ('plan_days', models.IntegerField(choices=[(3, '3 Days'), (7, '7 Days'), (15, '15 Days'), (30, '30 Days')])),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('lunch_off', models.BooleanField(default=False)),
                ('dinner_off', models.BooleanField(default=False)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium')], max_length=7)),
                ('meal_type', models.CharField(choices=[('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=6)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
