# Generated by Django 4.2.13 on 2024-05-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbear_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
